//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pocketRT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pocketRT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Through a discreet reminder of doing a reality test at certain intervals application helps to form the habit of doing it which increases the chances of reaching a lucid dream.
        ///
        ///Author: Krystian Kościelniak
        ///http://pocketrt.codeplex.com.
        /// </summary>
        internal static string aboutText {
            get {
                return ResourceManager.GetString("aboutText", resourceCulture);
            }
        }
        
        internal static byte[] alert {
            get {
                object obj = ResourceManager.GetObject("alert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s time for reality test, remember?.
        /// </summary>
        internal static string defaultCommunique {
            get {
                return ResourceManager.GetString("defaultCommunique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s time to check whether there is Sasquatch behind you.
        ///I wonder if you are able to penetrate me.
        ///What? Not ... I&apos;m sure the sky is not pink.
        ///What time is it? ...and now what&apos;s the time?
        ///I wonder what would you do if you had a $ 1000000 in your pocket.
        ///You can&apos;t fly or walk on water... can you?
        ///If I were you I&apos;d check if gravity works as it should.
        ///Hey, who you see in a mirror? Do you see the mirror?
        ///Come on! Do the reality test, now!.
        /// </summary>
        internal static string defaultCommuniqueList {
            get {
                return ResourceManager.GetString("defaultCommuniqueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string disabledMenuItemText {
            get {
                return ResourceManager.GetString("disabledMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string disableMenuItemText {
            get {
                return ResourceManager.GetString("disableMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string enabledMenuItemText {
            get {
                return ResourceManager.GetString("enabledMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string enableMenuItemText {
            get {
                return ResourceManager.GetString("enableMenuItemText", resourceCulture);
            }
        }
    }
}
